[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0-alpha.5"
edition = "2024"
rust-version = "1.95"
license = "GPL-3.0-or-later"
repository = "https://github.com/lorica-labs/volant"
homepage = "https://github.com/lorica-labs/volant"
authors = ["Hugo Planque"]

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"
unused_qualifications = "warn"

[workspace.lints.clippy]
assigning_clones = "warn"
default_trait_access = "warn"
format_collect = "warn"
format_push_string = "warn"
ignored_unit_patterns = "warn"
implicit_clone = "warn"
manual_let_else = "warn"
map_unwrap_or = "warn"
match_bool = "warn"
match_same_arms = "warn"
needless_continue = "warn"
needless_raw_string_hashes = "warn"
redundant_closure_for_method_calls = "warn"
ref_option = "warn"
semicolon_if_nothing_returned = "warn"
single_match_else = "warn"
trivially_copy_pass_by_ref = "warn"
unnested_or_patterns = "warn"

[workspace.dependencies]
anstream = "1"
anstyle = "1"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
insta = { version = "1", features = ["filters"] }
libc = "0.2"
minijinja = { version = "2", features = ["preserve_order"] }
regex = "1"
saphyr = "0.0.12"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
shlex = "2"
tokio = { version = "1", features = [
  "rt-multi-thread",
  "macros",
  "process",
  "io-util",
  "sync",
  "signal",
  "time",
] }
volant-protocol = { path = "crates/volant-protocol", version = "0.1.0-alpha.5" }

[profile.dev]
debug = "line-tables-only"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "fat"
