[package]
name = "volant"
description = "Fast, drop-in engine for Ansible playbooks"
readme = "../../README.md"
keywords = ["ansible", "automation", "ssh", "config-management"]
categories = ["command-line-utilities"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
build = "build.rs"

[dependencies]
anstream.workspace = true
anstyle.workspace = true
anyhow.workspace = true
clap.workspace = true
minijinja.workspace = true
regex.workspace = true
saphyr.workspace = true
serde_json.workspace = true
shlex.workspace = true
tokio.workspace = true
volant-protocol.workspace = true

[dev-dependencies]
insta.workspace = true

[[bin]]
name = "volant-playbook"
path = "src/bin/volant-playbook.rs"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }.tar.xz"
bin-dir = "{ name }-{ target }/{ bin }{ binary-ext }"
pkg-fmt = "txz"
